experiments:

  total_hourly:

    dataset: base_dataset_hourly
    target: rental_count
    models:

      linear_regression:

        features:
          numeric:
            - temperature_c
            - perceived_temperature_c

          categorical:
            - conditions
            - season

          boolean:
            - is_holiday
            - is_weekend

          cyclic:
            - hour_sin
            - hour_cos
            - weekday_sin
            - weekday_cos
            - month_sin
            - month_cos

          id_columns:

        preprocessing:
          scale_numeric: true
          one_hot_encode: true
          impute_numeric: null
          impute_categorical: null
          remove_low_variance: false

    

      random_forest:

        features:
          numeric:
            - temperature_c
            - perceived_temperature_c
            - humidity
            - windspeed_kmh

          categorical:
            - conditions
            - season

          boolean:
            - is_holiday
            - is_weekend

          cyclic:
            - hour_sin
            - hour_cos
            - weekday_sin
            - weekday_cos
            - month_sin
            - month_cos

          id_columns:

        preprocessing:
          scale_numeric: false
          one_hot_encode: true
          impute_numeric: null
          impute_categorical: null
          remove_low_variance: false



      xgboost:

        features:
          numeric:
            - temperature_c
            - perceived_temperature_c
            - humidity
            - windspeed_kmh

          categorical:
            - conditions
            - season

          boolean:
            - is_holiday
            - is_weekend

          cyclic:
            - hour_sin
            - hour_cos
            - weekday_sin
            - weekday_cos
            - month_sin
            - month_cos

          id_columns:

        preprocessing:
          scale_numeric: false
          one_hot_encode: false
          impute_numeric: median
          impute_categorical: most_frequent
          remove_low_variance: false
