features:
  hourly:
    numeric:
      - temperature_c
      - perceived_temperature_c
      - humidity
      - windspeed_kmh

    cyclic:
      hour:
        sin: hour_sin
        cos: hour_cos

      weekday:
        sin: weekday_sin
        cos: weekday_cos

      month:
        sin: month_sin
        cos: month_cos

    boolean:
      - is_holiday
      - is_weekend


targets:
  total_rentals: rental_count
  direct_rentals: direct_rentals
  registered_rentals: registered_rentals